server:
  max-http-header-size: 8192
  port: 8081

spring:
  application:
    name: mybatis-demo-8080
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atguigudb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml